//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MyWebApplication.ProxyDeliveries {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DeliveriesWSSoap", Namespace="http://tempuri.org/")]
    public partial class DeliveriesWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertDeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeliveryStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoreDeliveriesByStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DeliveriesWS() {
            this.Url = global::MyWebApplication.Properties.Settings.Default.MyWebApplication_ProxyDeliveries_DeliveriesWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertDeliveryCompletedEventHandler InsertDeliveryCompleted;
        
        /// <remarks/>
        public event GetDeliveryStatusCompletedEventHandler GetDeliveryStatusCompleted;
        
        /// <remarks/>
        public event GetStoreDeliveriesByStatusCompletedEventHandler GetStoreDeliveriesByStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertDelivery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertDelivery(Delivery d) {
            object[] results = this.Invoke("InsertDelivery", new object[] {
                        d});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertDeliveryAsync(Delivery d) {
            this.InsertDeliveryAsync(d, null);
        }
        
        /// <remarks/>
        public void InsertDeliveryAsync(Delivery d, object userState) {
            if ((this.InsertDeliveryOperationCompleted == null)) {
                this.InsertDeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertDeliveryOperationCompleted);
            }
            this.InvokeAsync("InsertDelivery", new object[] {
                        d}, this.InsertDeliveryOperationCompleted, userState);
        }
        
        private void OnInsertDeliveryOperationCompleted(object arg) {
            if ((this.InsertDeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertDeliveryCompleted(this, new InsertDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeliveryStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetDeliveryStatus(Delivery d) {
            object[] results = this.Invoke("GetDeliveryStatus", new object[] {
                        d});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetDeliveryStatusAsync(Delivery d) {
            this.GetDeliveryStatusAsync(d, null);
        }
        
        /// <remarks/>
        public void GetDeliveryStatusAsync(Delivery d, object userState) {
            if ((this.GetDeliveryStatusOperationCompleted == null)) {
                this.GetDeliveryStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeliveryStatusOperationCompleted);
            }
            this.InvokeAsync("GetDeliveryStatus", new object[] {
                        d}, this.GetDeliveryStatusOperationCompleted, userState);
        }
        
        private void OnGetDeliveryStatusOperationCompleted(object arg) {
            if ((this.GetDeliveryStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeliveryStatusCompleted(this, new GetDeliveryStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStoreDeliveriesByStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetStoreDeliveriesByStatus(int idStore, int status) {
            object[] results = this.Invoke("GetStoreDeliveriesByStatus", new object[] {
                        idStore,
                        status});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetStoreDeliveriesByStatusAsync(int idStore, int status) {
            this.GetStoreDeliveriesByStatusAsync(idStore, status, null);
        }
        
        /// <remarks/>
        public void GetStoreDeliveriesByStatusAsync(int idStore, int status, object userState) {
            if ((this.GetStoreDeliveriesByStatusOperationCompleted == null)) {
                this.GetStoreDeliveriesByStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoreDeliveriesByStatusOperationCompleted);
            }
            this.InvokeAsync("GetStoreDeliveriesByStatus", new object[] {
                        idStore,
                        status}, this.GetStoreDeliveriesByStatusOperationCompleted, userState);
        }
        
        private void OnGetStoreDeliveriesByStatusOperationCompleted(object arg) {
            if ((this.GetStoreDeliveriesByStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoreDeliveriesByStatusCompleted(this, new GetStoreDeliveriesByStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Delivery {
        
        private int iDDeliveryField;
        
        private int iDStoreField;
        
        private int iDOrderField;
        
        private System.DateTime statusDateField;
        
        private string custNameField;
        
        private string custAddressField;
        
        private string custPhoneField;
        
        private int statusField;
        
        /// <remarks/>
        public int IDDelivery {
            get {
                return this.iDDeliveryField;
            }
            set {
                this.iDDeliveryField = value;
            }
        }
        
        /// <remarks/>
        public int IDStore {
            get {
                return this.iDStoreField;
            }
            set {
                this.iDStoreField = value;
            }
        }
        
        /// <remarks/>
        public int IDOrder {
            get {
                return this.iDOrderField;
            }
            set {
                this.iDOrderField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StatusDate {
            get {
                return this.statusDateField;
            }
            set {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        public string CustName {
            get {
                return this.custNameField;
            }
            set {
                this.custNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustAddress {
            get {
                return this.custAddressField;
            }
            set {
                this.custAddressField = value;
            }
        }
        
        /// <remarks/>
        public string CustPhone {
            get {
                return this.custPhoneField;
            }
            set {
                this.custPhoneField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void InsertDeliveryCompletedEventHandler(object sender, InsertDeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertDeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertDeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetDeliveryStatusCompletedEventHandler(object sender, GetDeliveryStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeliveryStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeliveryStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetStoreDeliveriesByStatusCompletedEventHandler(object sender, GetStoreDeliveriesByStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoreDeliveriesByStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoreDeliveriesByStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591